### ISSUE TITLE
Fix screen "Welcome to nginx!"

### ISSUE THREAD

**Issue by helenaferens** [lidel/pls.watch#287]
When I used address: https://www.pls.watch/#v=OwWT43Eb3IM&t=1h14m36s
it showed screen:

**Mozilla Firefox 59.0.2**
![nginx-pls-watch](https://user-images.githubusercontent.com/37894892/38075640-53866ca0-3333-11e8-80e1-f9d5caf361ed.png)

the same on Chrome 65.0.3325.18

**Comment by lidel** [comment]
Thank you for reporting this, we were missing support for the `www.` subdomain. 
Should be fixed now, enjoy!
